let cityState = [
'Columbus, Ohio',
"Boca Raton, Florida",
'Florence, South Carolina',
"Rancho Cucamonga, California",
"Warren, Ohio",
"Akron, Ohio",
'Albany, Oregon',
'Rio Rancho, New Mexico',
'Moline, Illinois',
'Sacramento, California',
'Jurupa Valley, California',
'Haltom City, Texas',
'Cutler Bay, Florida',
'Florence, South Carolina',
'Vacaville, California',
'Jefferson City, Missouri',
'Florence, Alabama',
'Rockford, Illinois',
'Rialto, California',
'Kalamazoo, Michigan',
'Huber Heights, Ohio',
'Centennial, Colorado',
'Appleton, Wisconsin',
'Rochester Hills, Michigan',
'Irving, Texas',
'Abilene, Texas',
'Tucson, Arizona',
'Springfield, Missouri',
'Paterson, New Jersey',
'Oshkosh, Wisconsin',
'Lansing, Michigan',
'Vineland, New Jersey',
'Edina, Minnesota',
'Westfield, Massachusetts',
'Grand Junction, Colorado',
'Springdale, Arkansas',
'Lynn, Massachusetts',
'Tinley Park, Illinois',
'Chattanooga, Tennessee',
'La Habra, California',
'Portsmouth, Virginia',
'Macon, Georgia',
'Newark, California',
'White Plains, New York',
'Friendswood, Texas',
'Monroe, Louisiana',
'Nashville - Davidson, Tennessee',
'Los Angeles, California',
'Atlantic City, New Jersey',
'Middletown, Ohio',
'Miramar, Florida',
'Plymouth, Minnesota',
'Sunrise, Florida',
'Santa Clarita, California',
'Mesquite, Texas',
'Omaha, Nebraska',
'Palm Beach Gardens, Florida',
'Norfolk, Virginia',
'St.Cloud, Florida',
'Atlanta, Georgia',
'Boulder, Colorado',
'Taunton, Massachusetts',
'Pembroke Pines, Florida',
'Lehi, Utah',
'Palmdale, California',
'Calexico, California',
'Weymouth Town, Massachusetts',
'Woodbury, Minnesota',
'Amarillo, Texas',
'Shakopee, Minnesota',
'Erie, Pennsylvania',
'Mission Viejo, California',
'Hampton, Virginia',
'Great Falls, Montana',
'Kennewick, Washington',
'Mansfield, Ohio',
'Walnut Creek, California',
'Tampa, Florida',
'Boulder, Colorado',
'Warren, Michigan',
'Springfield, Ohio',
'Rosemead, California',
'Dothan, Alabama',
'Warren, Michigan',
'San Marcos, Texas',
'Waltham, Massachusetts',
'Frederick, Maryland',
'Denton, Texas',
'Bountiful, Utah',
'Diamond Bar, California',
'Citrus Heights, California',
'Cuyahoga Falls, Ohio',
'San Francisco, California',
'Deerfield Beach, Florida',
'Chino Hills, California',
'Shreveport, Louisiana',
'Portage, Michigan',
'Suffolk, Virginia',
'Alameda, California',]